[package]
name = "nasubot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.23", features = ["derive", "env"]}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sysinfo = "0.33.0"